data:
  lookback_period: 100
  timeframes:
    - 1d
    - 1h
assets:
  - BTC
  - SOL
  - SUI
  - SEI
data_urls:
  BTC:
    raw: https://raw.githubusercontent.com/Zombie-3000/Bitfinex-historical-data/master/BTCUSD/Candles_1m/2013/merged.csv
