data:
  lookback_period: 100
  timeframes:
    - 1d
    - 1h
assets:
  - BTC
  - SOL
  - SUI
  - SEI
data_urls: {}

sui_rpc: https://fullnode.mainnet.sui.io
grok_api_key: "SECRET_REMOVED"
mcp_port: 8000